---
- name: Deploy Python Calculator
  hosts: localhost
  remote_user: deepanshpandey
  become: false
  environment:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  tasks:

    - name: Pull the latest Docker image
      community.general.docker_image:
        name: coffeeinacafe/calpy
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Stop and remove existing container if running
      shell: docker stop calpy && docker rm calpy

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calpy coffeeinacafe/calpy