---
- name: Deploy Python Calculator
  hosts: localhost
  become: yes  # Ensures sudo is used for Docker commands
  environment:
    DOCKER_HOST: "unix:///var/run/docker.sock"  # Ensure Ansible connects to Docker correctly
  tasks:
  
    - name: Install required Python libraries for Docker
      pip:
        name:
          - docker
          - docker-compose
        state: present

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: "coffeeinacafe/calpy"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Stop and remove existing container if running
      community.docker.docker_container:
        name: calpy
        state: absent

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start a new Docker container
      community.docker.docker_container:
        name: calpy
        image: coffeeinacafe/calpy
        state: started
        restart_policy: always
        detach: yes  # Runs the container in the background
